branch-defaults:
  default:
    environment: ProjectXsite-dev
    group_suffix: null
global:
  application_name: ProjectXsite
  branch: null
  default_ec2_keyname: MLtestPK
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
